export type CivicsSection =
  | "American Government"
  | "American History"
  | "Symbols and Holidays";

export type CivicsQuestion = {
  id: number;
  section: CivicsSection;
  question: string;
  answers: string[];
  need: number;
  special65?: boolean;
  varies?: boolean;
  currentOfficial?: boolean;
};

export const civicsSourceUrl =
  "https://www.uscis.gov/citizenship-resource-center/naturalization-test-and-study-resources/2025-civics-test";

export const civicsUpdatesUrl = "https://www.uscis.gov/citizenship/testupdates";

export const civicsQuestions: CivicsQuestion[] = [
  {
    id: 1,
    section: "American Government",
    question: "What is the form of government of the United States?",
    answers: [
      "Republic",
      "Constitution-based federal republic",
      "Representative democracy",
    ],
    need: 1,
  },
  {
    id: 2,
    section: "American Government",
    question: "What is the supreme law of the land?",
    answers: ["(U.S.) Constitution", "Constitution", "U.S. Constitution"],
    need: 1,
    special65: true,
  },
  {
    id: 3,
    section: "American Government",
    question: "Name one thing the U.S. Constitution does.",
    answers: [
      "Forms the government",
      "Defines powers of government",
      "Defines the parts of government",
      "Protects the rights of the people",
    ],
    need: 1,
  },
  {
    id: 4,
    section: "American Government",
    question: 'The U.S. Constitution starts with the words “We the People.” What does “We the People” mean?',
    answers: [
      "Self-government",
      "Popular sovereignty",
      "Consent of the governed",
      "People should govern themselves",
      "(Example of) social contract",
      "Social contract",
    ],
    need: 1,
  },
  {
    id: 5,
    section: "American Government",
    question: "How are changes made to the U.S. Constitution?",
    answers: ["Amendments", "The amendment process"],
    need: 1,
  },
  {
    id: 6,
    section: "American Government",
    question: "What does the Bill of Rights protect?",
    answers: [
      "(The basic) rights of Americans",
      "The basic rights of Americans",
      "(The basic) rights of people living in the United States",
      "The basic rights of people living in the United States",
    ],
    need: 1,
  },
  {
    id: 7,
    section: "American Government",
    question: "How many amendments does the U.S. Constitution have?",
    answers: ["Twenty-seven (27)", "Twenty-seven", "27"],
    need: 1,
    special65: true,
  },
  {
    id: 8,
    section: "American Government",
    question: "Why is the Declaration of Independence important?",
    answers: [
      "It says America is free from British control.",
      "It says all people are created equal.",
      "It identifies inherent rights.",
      "It identifies individual freedoms.",
    ],
    need: 1,
  },
  {
    id: 9,
    section: "American Government",
    question: "What founding document said the American colonies were free from Britain?",
    answers: ["Declaration of Independence"],
    need: 1,
  },
  {
    id: 10,
    section: "American Government",
    question:
      "Name two important ideas from the Declaration of Independence and the U.S. Constitution.",
    answers: [
      "Equality",
      "Liberty",
      "Social contract",
      "Natural rights",
      "Limited government",
      "Self-government",
    ],
    need: 2,
  },
  {
    id: 11,
    section: "American Government",
    question:
      'The words “Life, Liberty, and the pursuit of Happiness” are in what founding document?',
    answers: ["Declaration of Independence"],
    need: 1,
  },
  {
    id: 12,
    section: "American Government",
    question: "What is the economic system of the United States?",
    answers: ["Capitalism", "Free market economy"],
    need: 1,
    special65: true,
  },
  {
    id: 13,
    section: "American Government",
    question: "What is the rule of law?",
    answers: [
      "Everyone must follow the law.",
      "Leaders must obey the law.",
      "Government must obey the law.",
      "No one is above the law.",
    ],
    need: 1,
  },
  {
    id: 14,
    section: "American Government",
    question: "Many documents influenced the U.S. Constitution. Name one.",
    answers: [
      "Declaration of Independence",
      "Articles of Confederation",
      "Federalist Papers",
      "Anti-Federalist Papers",
      "Virginia Declaration of Rights",
      "Fundamental Orders of Connecticut",
      "Mayflower Compact",
      "Iroquois Great Law of Peace",
    ],
    need: 1,
  },
  {
    id: 15,
    section: "American Government",
    question: "There are three branches of government. Why?",
    answers: [
      "So one part does not become too powerful",
      "Checks and balances",
      "Separation of powers",
    ],
    need: 1,
  },
  {
    id: 16,
    section: "American Government",
    question: "Name the three branches of government.",
    answers: [
      "Legislative, executive, and judicial",
      "Congress, president, and the courts",
    ],
    need: 1,
  },
  {
    id: 17,
    section: "American Government",
    question: "The President of the United States is in charge of which branch of government?",
    answers: ["Executive branch"],
    need: 1,
  },
  {
    id: 18,
    section: "American Government",
    question: "What part of the federal government writes laws?",
    answers: [
      "(U.S.) Congress",
      "Congress",
      "U.S. Congress",
      "(U.S. or national) legislature",
      "Legislature",
      "Legislative branch",
    ],
    need: 1,
  },
  {
    id: 19,
    section: "American Government",
    question: "What are the two parts of the U.S. Congress?",
    answers: [
      "Senate and House (of Representatives)",
      "Senate and House of Representatives",
      "The Senate and the House",
    ],
    need: 1,
  },
  {
    id: 20,
    section: "American Government",
    question: "Name one power of the U.S. Congress.",
    answers: ["Writes laws", "Declares war", "Makes the federal budget"],
    need: 1,
    special65: true,
  },
  {
    id: 21,
    section: "American Government",
    question: "How many U.S. senators are there?",
    answers: ["One hundred (100)", "One hundred", "100"],
    need: 1,
  },
  {
    id: 22,
    section: "American Government",
    question: "How long is a term for a U.S. senator?",
    answers: ["Six (6) years", "Six years", "6 years"],
    need: 1,
  },
  {
    id: 23,
    section: "American Government",
    question: "Who is one of your state’s U.S. senators now?",
    answers: [
      "Answers vary by state. D.C. and U.S. territory residents should say they have no U.S. senators.",
    ],
    need: 1,
    varies: true,
  },
  {
    id: 24,
    section: "American Government",
    question: "How many voting members are in the House of Representatives?",
    answers: [
      "Four hundred thirty-five (435)",
      "Four hundred thirty-five",
      "435",
    ],
    need: 1,
  },
  {
    id: 25,
    section: "American Government",
    question: "How long is a term for a member of the House of Representatives?",
    answers: ["Two (2) years", "Two years", "2 years"],
    need: 1,
  },
  {
    id: 26,
    section: "American Government",
    question: "Why do U.S. representatives serve shorter terms than U.S. senators?",
    answers: ["To more closely follow public opinion"],
    need: 1,
  },
  {
    id: 27,
    section: "American Government",
    question: "How many senators does each state have?",
    answers: ["Two (2)", "Two", "2"],
    need: 1,
  },
  {
    id: 28,
    section: "American Government",
    question: "Why does each state have two senators?",
    answers: [
      "Equal representation (for small states)",
      "Equal representation for small states",
      "The Great Compromise (Connecticut Compromise)",
      "The Great Compromise",
      "Connecticut Compromise",
    ],
    need: 1,
  },
  {
    id: 29,
    section: "American Government",
    question: "Name your U.S. representative.",
    answers: [
      "Answers vary. Territory residents may name their nonvoting Delegate or Resident Commissioner, or say they have no voting representative.",
    ],
    need: 1,
    varies: true,
  },
  {
    id: 30,
    section: "American Government",
    question: "What is the name of the Speaker of the House of Representatives now?",
    answers: ["Mike Johnson", "Johnson"],
    need: 1,
    special65: true,
    currentOfficial: true,
  },
  {
    id: 31,
    section: "American Government",
    question: "Who does a U.S. senator represent?",
    answers: ["Citizens of their state", "People of their state"],
    need: 1,
  },
  {
    id: 32,
    section: "American Government",
    question: "Who elects U.S. senators?",
    answers: ["Citizens from their state"],
    need: 1,
  },
  {
    id: 33,
    section: "American Government",
    question: "Who does a member of the House of Representatives represent?",
    answers: [
      "Citizens in their (congressional) district",
      "Citizens in their congressional district",
      "Citizens in their district",
      "People from their (congressional) district",
      "People from their congressional district",
      "People in their district",
    ],
    need: 1,
  },
  {
    id: 34,
    section: "American Government",
    question: "Who elects members of the House of Representatives?",
    answers: [
      "Citizens from their (congressional) district",
      "Citizens from their congressional district",
    ],
    need: 1,
  },
  {
    id: 35,
    section: "American Government",
    question: "Some states have more representatives than other states. Why?",
    answers: [
      "(Because of) the state’s population",
      "Because of the state's population",
      "(Because) they have more people",
      "Because they have more people",
      "(Because) some states have more people",
      "Because some states have more people",
    ],
    need: 1,
  },
  {
    id: 36,
    section: "American Government",
    question: "The President of the United States is elected for how many years?",
    answers: ["Four (4) years", "Four years", "4 years"],
    need: 1,
    special65: true,
  },
  {
    id: 37,
    section: "American Government",
    question: "The President of the United States can serve only two terms. Why?",
    answers: [
      "(Because of) the 22nd Amendment",
      "Because of the 22nd Amendment",
      "22nd Amendment",
      "To keep the president from becoming too powerful",
    ],
    need: 1,
  },
  {
    id: 38,
    section: "American Government",
    question: "What is the name of the President of the United States now?",
    answers: [
      "Donald J. Trump",
      "Donald Trump",
      "Trump",
    ],
    need: 1,
    special65: true,
    currentOfficial: true,
  },
  {
    id: 39,
    section: "American Government",
    question: "What is the name of the Vice President of the United States now?",
    answers: ["JD Vance", "J.D. Vance", "Vance"],
    need: 1,
    special65: true,
    currentOfficial: true,
  },
  {
    id: 40,
    section: "American Government",
    question: "If the president can no longer serve, who becomes president?",
    answers: [
      "The Vice President (of the United States)",
      "The Vice President",
      "Vice President",
    ],
    need: 1,
  },
  {
    id: 41,
    section: "American Government",
    question: "Name one power of the president.",
    answers: [
      "Signs bills into law",
      "Vetoes bills",
      "Enforces laws",
      "Commander in Chief (of the military)",
      "Commander in Chief",
      "Chief diplomat",
      "Appoints federal judges",
    ],
    need: 1,
  },
  {
    id: 42,
    section: "American Government",
    question: "Who is Commander in Chief of the U.S. military?",
    answers: [
      "The President (of the United States)",
      "The President",
      "President",
    ],
    need: 1,
  },
  {
    id: 43,
    section: "American Government",
    question: "Who signs bills to become laws?",
    answers: [
      "The President (of the United States)",
      "The President",
      "President",
    ],
    need: 1,
  },
  {
    id: 44,
    section: "American Government",
    question: "Who vetoes bills?",
    answers: [
      "The President (of the United States)",
      "The President",
      "President",
    ],
    need: 1,
    special65: true,
  },
  {
    id: 45,
    section: "American Government",
    question: "Who appoints federal judges?",
    answers: [
      "The President (of the United States)",
      "The President",
      "President",
    ],
    need: 1,
  },
  {
    id: 46,
    section: "American Government",
    question: "The executive branch has many parts. Name one.",
    answers: [
      "President (of the United States)",
      "President",
      "Cabinet",
      "Federal departments and agencies",
    ],
    need: 1,
  },
  {
    id: 47,
    section: "American Government",
    question: "What does the President’s Cabinet do?",
    answers: [
      "Advises the President (of the United States)",
      "Advises the President",
    ],
    need: 1,
  },
  {
    id: 48,
    section: "American Government",
    question: "What are two Cabinet-level positions?",
    answers: [
      "Attorney General",
      "Secretary of Agriculture",
      "Secretary of Commerce",
      "Secretary of Education",
      "Secretary of Energy",
      "Secretary of Health and Human Services",
      "Secretary of Homeland Security",
      "Secretary of Housing and Urban Development",
      "Secretary of the Interior",
      "Secretary of Labor",
      "Secretary of State",
      "Secretary of Transportation",
      "Secretary of the Treasury",
      "Secretary of Veterans Affairs",
      "Secretary of War (Defense)",
      "Secretary of War",
      "Secretary of Defense",
      "Vice-President",
      "Vice President",
      "Administrator of the Environmental Protection Agency",
      "Administrator of the Small Business Administration",
      "Director of the Central Intelligence Agency",
      "Director of the Office of Management and Budget",
      "Director of National Intelligence",
      "United States Trade Representative",
    ],
    need: 2,
  },
  {
    id: 49,
    section: "American Government",
    question: "Why is the Electoral College important?",
    answers: [
      "It decides who is elected president.",
      "It provides a compromise between the popular election of the president and congressional selection.",
    ],
    need: 1,
  },
  {
    id: 50,
    section: "American Government",
    question: "What is one part of the judicial branch?",
    answers: ["Supreme Court", "Federal Courts"],
    need: 1,
  },
  {
    id: 51,
    section: "American Government",
    question: "What does the judicial branch do?",
    answers: [
      "Reviews laws",
      "Explains laws",
      "Resolves disputes (disagreements) about the law",
      "Resolves disputes about the law",
      "Decides if a law goes against the (U.S.) Constitution",
      "Decides if a law goes against the Constitution",
    ],
    need: 1,
  },
  {
    id: 52,
    section: "American Government",
    question: "What is the highest court in the United States?",
    answers: ["Supreme Court"],
    need: 1,
    special65: true,
  },
  {
    id: 53,
    section: "American Government",
    question: "How many seats are on the Supreme Court?",
    answers: ["Nine (9)", "Nine", "9"],
    need: 1,
  },
  {
    id: 54,
    section: "American Government",
    question: "How many Supreme Court justices are usually needed to decide a case?",
    answers: ["Five (5)", "Five", "5"],
    need: 1,
  },
  {
    id: 55,
    section: "American Government",
    question: "How long do Supreme Court justices serve?",
    answers: ["(For) life", "For life", "Lifetime appointment", "(Until) retirement", "Until retirement"],
    need: 1,
  },
  {
    id: 56,
    section: "American Government",
    question: "Supreme Court justices serve for life. Why?",
    answers: [
      "To be independent (of politics)",
      "To be independent of politics",
      "To limit outside (political) influence",
      "To limit outside political influence",
    ],
    need: 1,
  },
  {
    id: 57,
    section: "American Government",
    question: "Who is the Chief Justice of the United States now?",
    answers: [
      "John Roberts",
      "John G. Roberts",
      "John G. Roberts, Jr.",
      "Roberts",
    ],
    need: 1,
    currentOfficial: true,
  },
  {
    id: 58,
    section: "American Government",
    question: "Name one power that is only for the federal government.",
    answers: [
      "Print paper money",
      "Mint coins",
      "Declare war",
      "Create an army",
      "Make treaties",
      "Set foreign policy",
    ],
    need: 1,
  },
  {
    id: 59,
    section: "American Government",
    question: "Name one power that is only for the states.",
    answers: [
      "Provide schooling and education",
      "Provide protection (police)",
      "Provide protection",
      "Provide safety (fire departments)",
      "Provide safety",
      "Give a driver’s license",
      "Give a driver's license",
      "Approve zoning and land use",
    ],
    need: 1,
  },
  {
    id: 60,
    section: "American Government",
    question: "What is the purpose of the 10th Amendment?",
    answers: [
      "(It states that the) powers not given to the federal government belong to the states or to the people.",
      "Powers not given to the federal government belong to the states or to the people",
    ],
    need: 1,
  },
  {
    id: 61,
    section: "American Government",
    question: "Who is the governor of your state now?",
    answers: [
      "Answers vary by state. District of Columbia residents should answer that D.C. does not have a governor.",
    ],
    need: 1,
    special65: true,
    varies: true,
  },
  {
    id: 62,
    section: "American Government",
    question: "What is the capital of your state?",
    answers: [
      "Answers vary. D.C. is not a state and does not have a capital. Territory residents should name the capital of the territory.",
    ],
    need: 1,
    varies: true,
  },
  {
    id: 63,
    section: "American Government",
    question:
      "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.",
    answers: [
      "Citizens eighteen (18) and older (can vote).",
      "Citizens eighteen and older can vote",
      "You don’t have to pay (a poll tax) to vote.",
      "You don't have to pay a poll tax to vote",
      "Any citizen can vote. (Women and men can vote.)",
      "Any citizen can vote",
      "A male citizen of any race (can vote).",
      "A male citizen of any race can vote",
    ],
    need: 1,
  },
  {
    id: 64,
    section: "American Government",
    question:
      "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?",
    answers: ["Citizens", "Citizens of the United States", "U.S. citizens"],
    need: 1,
  },
  {
    id: 65,
    section: "American Government",
    question: "What are three rights of everyone living in the United States?",
    answers: [
      "Freedom of expression",
      "Freedom of speech",
      "Freedom of assembly",
      "Freedom to petition the government",
      "Freedom of religion",
      "The right to bear arms",
    ],
    need: 3,
  },
  {
    id: 66,
    section: "American Government",
    question: "What do we show loyalty to when we say the Pledge of Allegiance?",
    answers: ["The United States", "The flag"],
    need: 1,
    special65: true,
  },
  {
    id: 67,
    section: "American Government",
    question: "Name two promises that new citizens make in the Oath of Allegiance.",
    answers: [
      "Give up loyalty to other countries",
      "Defend the (U.S.) Constitution",
      "Defend the Constitution",
      "Obey the laws of the United States",
      "Serve in the military (if needed)",
      "Serve in the military if needed",
      "Serve (help, do important work for) the nation (if needed)",
      "Serve the nation if needed",
      "Be loyal to the United States",
    ],
    need: 2,
  },
  {
    id: 68,
    section: "American Government",
    question: "How can people become United States citizens?",
    answers: [
      "Be born in the United States, under the conditions set by the 14th Amendment",
      "Naturalize",
      "Derive citizenship (under conditions set by Congress)",
      "Derive citizenship",
    ],
    need: 1,
  },
  {
    id: 69,
    section: "American Government",
    question: "What are two examples of civic participation in the United States?",
    answers: [
      "Vote",
      "Run for office",
      "Join a political party",
      "Help with a campaign",
      "Join a civic group",
      "Join a community group",
      "Give an elected official your opinion (on an issue)",
      "Give an elected official your opinion",
      "Contact elected officials",
      "Support or oppose an issue or policy",
      "Write to a newspaper",
    ],
    need: 2,
  },
  {
    id: 70,
    section: "American Government",
    question: "What is one way Americans can serve their country?",
    answers: [
      "Vote",
      "Pay taxes",
      "Obey the law",
      "Serve in the military",
      "Run for office",
      "Work for local, state, or federal government",
    ],
    need: 1,
  },
  {
    id: 71,
    section: "American Government",
    question: "Why is it important to pay federal taxes?",
    answers: [
      "Required by law",
      "All people pay to fund the federal government",
      "Required by the (U.S.) Constitution (16th Amendment)",
      "Required by the Constitution",
      "Civic duty",
    ],
    need: 1,
  },
  {
    id: 72,
    section: "American Government",
    question:
      "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.",
    answers: [
      "Required by law",
      "Civic duty",
      "Makes the draft fair, if needed",
    ],
    need: 1,
  },
  {
    id: 73,
    section: "American History",
    question: "The colonists came to America for many reasons. Name one.",
    answers: [
      "Freedom",
      "Political liberty",
      "Religious freedom",
      "Economic opportunity",
      "Escape persecution",
    ],
    need: 1,
  },
  {
    id: 74,
    section: "American History",
    question: "Who lived in America before the Europeans arrived?",
    answers: ["American Indians", "Native Americans"],
    need: 1,
    special65: true,
  },
  {
    id: 75,
    section: "American History",
    question: "What group of people was taken and sold as slaves?",
    answers: ["Africans", "People from Africa"],
    need: 1,
  },
  {
    id: 76,
    section: "American History",
    question: "What war did the Americans fight to win independence from Britain?",
    answers: [
      "American Revolution",
      "The (American) Revolutionary War",
      "Revolutionary War",
      "War for (American) Independence",
      "War for American Independence",
    ],
    need: 1,
  },
  {
    id: 77,
    section: "American History",
    question: "Name one reason why the Americans declared independence from Britain.",
    answers: [
      "High taxes",
      "Taxation without representation",
      "British soldiers stayed in Americans’ houses (boarding, quartering)",
      "British soldiers stayed in Americans' houses",
      "They did not have self-government",
      "Boston Massacre",
      "Boston Tea Party (Tea Act)",
      "Boston Tea Party",
      "Stamp Act",
      "Sugar Act",
      "Townshend Acts",
      "Intolerable (Coercive) Acts",
      "Intolerable Acts",
    ],
    need: 1,
  },
  {
    id: 78,
    section: "American History",
    question: "Who wrote the Declaration of Independence?",
    answers: ["(Thomas) Jefferson", "Thomas Jefferson", "Jefferson"],
    need: 1,
    special65: true,
  },
  {
    id: 79,
    section: "American History",
    question: "When was the Declaration of Independence adopted?",
    answers: ["July 4, 1776", "July 4 1776"],
    need: 1,
  },
  {
    id: 80,
    section: "American History",
    question: "The American Revolution had many important events. Name one.",
    answers: [
      "(Battle of) Bunker Hill",
      "Battle of Bunker Hill",
      "Declaration of Independence",
      "Washington Crossing the Delaware (Battle of Trenton)",
      "Washington Crossing the Delaware",
      "Battle of Trenton",
      "(Battle of) Saratoga",
      "Battle of Saratoga",
      "Valley Forge (Encampment)",
      "Valley Forge",
      "(Battle of) Yorktown (British surrender at Yorktown)",
      "Battle of Yorktown",
    ],
    need: 1,
  },
  {
    id: 81,
    section: "American History",
    question: "There were 13 original states. Name five.",
    answers: [
      "New Hampshire",
      "Massachusetts",
      "Rhode Island",
      "Connecticut",
      "New York",
      "New Jersey",
      "Pennsylvania",
      "Delaware",
      "Maryland",
      "Virginia",
      "North Carolina",
      "South Carolina",
      "Georgia",
    ],
    need: 5,
  },
  {
    id: 82,
    section: "American History",
    question: "What founding document was written in 1787?",
    answers: ["(U.S.) Constitution", "U.S. Constitution", "Constitution"],
    need: 1,
  },
  {
    id: 83,
    section: "American History",
    question:
      "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
    answers: [
      "(James) Madison",
      "James Madison",
      "Madison",
      "(Alexander) Hamilton",
      "Alexander Hamilton",
      "Hamilton",
      "(John) Jay",
      "John Jay",
      "Jay",
      "Publius",
    ],
    need: 1,
  },
  {
    id: 84,
    section: "American History",
    question: "Why were the Federalist Papers important?",
    answers: [
      "They helped people understand the (U.S.) Constitution.",
      "They helped people understand the Constitution.",
      "They supported passing the (U.S.) Constitution.",
      "They supported passing the Constitution.",
    ],
    need: 1,
  },
  {
    id: 85,
    section: "American History",
    question: "Benjamin Franklin is famous for many things. Name one.",
    answers: [
      "Founded the first free public libraries",
      "First Postmaster General of the United States",
      "Helped write the Declaration of Independence",
      "Inventor",
      "U.S. diplomat",
    ],
    need: 1,
  },
  {
    id: 86,
    section: "American History",
    question: "George Washington is famous for many things. Name one.",
    answers: [
      "“Father of Our Country”",
      "Father of Our Country",
      "First president of the United States",
      "General of the Continental Army",
      "President of the Constitutional Convention",
    ],
    need: 1,
    special65: true,
  },
  {
    id: 87,
    section: "American History",
    question: "Thomas Jefferson is famous for many things. Name one.",
    answers: [
      "Writer of the Declaration of Independence",
      "Third president of the United States",
      "Doubled the size of the United States (Louisiana Purchase)",
      "Doubled the size of the United States",
      "First Secretary of State",
      "Founded the University of Virginia",
      "Writer of the Virginia Statute on Religious Freedom",
    ],
    need: 1,
  },
  {
    id: 88,
    section: "American History",
    question: "James Madison is famous for many things. Name one.",
    answers: [
      "“Father of the Constitution”",
      "Father of the Constitution",
      "Fourth president of the United States",
      "President during the War of 1812",
      "One of the writers of the Federalist Papers",
    ],
    need: 1,
  },
  {
    id: 89,
    section: "American History",
    question: "Alexander Hamilton is famous for many things. Name one.",
    answers: [
      "First Secretary of the Treasury",
      "One of the writers of the Federalist Papers",
      "Helped establish the First Bank of the United States",
      "Aide to General George Washington",
      "Member of the Continental Congress",
    ],
    need: 1,
  },
  {
    id: 90,
    section: "American History",
    question: "What territory did the United States buy from France in 1803?",
    answers: ["Louisiana Territory", "Louisiana"],
    need: 1,
  },
  {
    id: 91,
    section: "American History",
    question: "Name one war fought by the United States in the 1800s.",
    answers: [
      "War of 1812",
      "Mexican-American War",
      "Civil War",
      "Spanish-American War",
    ],
    need: 1,
  },
  {
    id: 92,
    section: "American History",
    question: "Name the U.S. war between the North and the South.",
    answers: ["The Civil War", "Civil War"],
    need: 1,
  },
  {
    id: 93,
    section: "American History",
    question: "The Civil War had many important events. Name one.",
    answers: [
      "(Battle of) Fort Sumter",
      "Battle of Fort Sumter",
      "Emancipation Proclamation",
      "(Battle of) Vicksburg",
      "Battle of Vicksburg",
      "(Battle of) Gettysburg",
      "Battle of Gettysburg",
      "Sherman’s March",
      "Sherman's March",
      "(Surrender at) Appomattox",
      "Surrender at Appomattox",
      "(Battle of) Antietam/Sharpsburg",
      "Battle of Antietam",
      "Lincoln was assassinated.",
    ],
    need: 1,
  },
  {
    id: 94,
    section: "American History",
    question: "Abraham Lincoln is famous for many things. Name one.",
    answers: [
      "Freed the slaves (Emancipation Proclamation)",
      "Freed the slaves",
      "Saved (or preserved) the Union",
      "Saved the Union",
      "Led the United States during the Civil War",
      "16th president of the United States",
      "Delivered the Gettysburg Address",
    ],
    need: 1,
    special65: true,
  },
  {
    id: 95,
    section: "American History",
    question: "What did the Emancipation Proclamation do?",
    answers: [
      "Freed the slaves",
      "Freed slaves in the Confederacy",
      "Freed slaves in the Confederate states",
      "Freed slaves in most Southern states",
    ],
    need: 1,
  },
  {
    id: 96,
    section: "American History",
    question: "What U.S. war ended slavery?",
    answers: ["The Civil War", "Civil War"],
    need: 1,
  },
  {
    id: 97,
    section: "American History",
    question:
      "What amendment says all persons born or naturalized in the United States, and subject to the jurisdiction thereof, are U.S. citizens?",
    answers: ["14th Amendment"],
    need: 1,
  },
  {
    id: 98,
    section: "American History",
    question: "When did all men get the right to vote?",
    answers: [
      "After the Civil War",
      "During Reconstruction",
      "(With the) 15th Amendment",
      "15th Amendment",
      "1870",
    ],
    need: 1,
  },
  {
    id: 99,
    section: "American History",
    question: "Name one leader of the women’s rights movement in the 1800s.",
    answers: [
      "Susan B. Anthony",
      "Elizabeth Cady Stanton",
      "Sojourner Truth",
      "Harriet Tubman",
      "Lucretia Mott",
      "Lucy Stone",
    ],
    need: 1,
  },
  {
    id: 100,
    section: "American History",
    question: "Name one war fought by the United States in the 1900s.",
    answers: [
      "World War I",
      "World War II",
      "Korean War",
      "Vietnam War",
      "(Persian) Gulf War",
      "Persian Gulf War",
      "Gulf War",
    ],
    need: 1,
  },
  {
    id: 101,
    section: "American History",
    question: "Why did the United States enter World War I?",
    answers: [
      "Because Germany attacked U.S. (civilian) ships",
      "Because Germany attacked U.S. civilian ships",
      "To support the Allied Powers (England, France, Italy, and Russia)",
      "To support the Allied Powers",
      "To oppose the Central Powers (Germany, Austria-Hungary, the Ottoman Empire, and Bulgaria)",
      "To oppose the Central Powers",
    ],
    need: 1,
  },
  {
    id: 102,
    section: "American History",
    question: "When did all women get the right to vote?",
    answers: [
      "1920",
      "After World War I",
      "(With the) 19th Amendment",
      "19th Amendment",
    ],
    need: 1,
  },
  {
    id: 103,
    section: "American History",
    question: "What was the Great Depression?",
    answers: ["Longest economic recession in modern history"],
    need: 1,
  },
  {
    id: 104,
    section: "American History",
    question: "When did the Great Depression start?",
    answers: ["The Great Crash (1929)", "The Great Crash", "Stock market crash of 1929"],
    need: 1,
  },
  {
    id: 105,
    section: "American History",
    question: "Who was president during the Great Depression and World War II?",
    answers: ["(Franklin) Roosevelt", "Franklin Roosevelt", "Franklin D. Roosevelt", "Roosevelt"],
    need: 1,
  },
  {
    id: 106,
    section: "American History",
    question: "Why did the United States enter World War II?",
    answers: [
      "(Bombing of) Pearl Harbor",
      "Bombing of Pearl Harbor",
      "Japanese attacked Pearl Harbor",
      "To support the Allied Powers (England, France, and Russia)",
      "To support the Allied Powers",
      "To oppose the Axis Powers (Germany, Italy, and Japan)",
      "To oppose the Axis Powers",
    ],
    need: 1,
  },
  {
    id: 107,
    section: "American History",
    question: "Dwight Eisenhower is famous for many things. Name one.",
    answers: [
      "General during World War II",
      "President at the end of (during) the Korean War",
      "President during the Korean War",
      "34th president of the United States",
      "Signed the Federal-Aid Highway Act of 1956 (Created the Interstate System)",
      "Signed the Federal-Aid Highway Act of 1956",
    ],
    need: 1,
  },
  {
    id: 108,
    section: "American History",
    question: "Who was the United States’ main rival during the Cold War?",
    answers: ["Soviet Union", "USSR", "Russia"],
    need: 1,
  },
  {
    id: 109,
    section: "American History",
    question: "During the Cold War, what was one main concern of the United States?",
    answers: ["Communism", "Nuclear war"],
    need: 1,
  },
  {
    id: 110,
    section: "American History",
    question: "Why did the United States enter the Korean War?",
    answers: ["To stop the spread of communism"],
    need: 1,
  },
  {
    id: 111,
    section: "American History",
    question: "Why did the United States enter the Vietnam War?",
    answers: ["To stop the spread of communism"],
    need: 1,
  },
  {
    id: 112,
    section: "American History",
    question: "What did the civil rights movement do?",
    answers: ["Fought to end racial discrimination"],
    need: 1,
  },
  {
    id: 113,
    section: "American History",
    question: "Martin Luther King, Jr. is famous for many things. Name one.",
    answers: [
      "Fought for civil rights",
      "Worked for equality for all Americans",
      'Worked to ensure that people would “not be judged by the color of their skin, but by the content of their character”',
    ],
    need: 1,
    special65: true,
  },
  {
    id: 114,
    section: "American History",
    question: "Why did the United States enter the Persian Gulf War?",
    answers: ["To force the Iraqi military from Kuwait"],
    need: 1,
  },
  {
    id: 115,
    section: "American History",
    question: "What major event happened on September 11, 2001 in the United States?",
    answers: [
      "Terrorists attacked the United States",
      "Terrorists took over two planes and crashed them into the World Trade Center in New York City",
      "Terrorists took over a plane and crashed into the Pentagon in Arlington, Virginia",
      "Terrorists took over a plane originally aimed at Washington, D.C., and crashed in a field in Pennsylvania",
    ],
    need: 1,
    special65: true,
  },
  {
    id: 116,
    section: "American History",
    question: "Name one U.S. military conflict after the September 11, 2001 attacks.",
    answers: [
      "(Global) War on Terror",
      "War on Terror",
      "War in Afghanistan",
      "War in Iraq",
    ],
    need: 1,
  },
  {
    id: 117,
    section: "American History",
    question: "Name one American Indian tribe in the United States.",
    answers: [
      "Apache",
      "Blackfeet",
      "Cayuga",
      "Cherokee",
      "Cheyenne",
      "Chippewa",
      "Choctaw",
      "Creek",
      "Crow",
      "Hopi",
      "Huron",
      "Inupiat",
      "Lakota",
      "Mohawk",
      "Mohegan",
      "Navajo",
      "Oneida",
      "Onondaga",
      "Pueblo",
      "Seminole",
      "Seneca",
      "Shawnee",
      "Sioux",
      "Teton",
      "Tuscarora",
    ],
    need: 1,
  },
  {
    id: 118,
    section: "American History",
    question: "Name one example of an American innovation.",
    answers: [
      "Light bulb",
      "Automobile (cars, internal combustion engine)",
      "Automobile",
      "Skyscrapers",
      "Airplane",
      "Assembly line",
      "Landing on the moon",
      "Integrated circuit (IC)",
      "Integrated circuit",
    ],
    need: 1,
  },
  {
    id: 119,
    section: "Symbols and Holidays",
    question: "What is the capital of the United States?",
    answers: ["Washington, D.C.", "Washington D.C.", "Washington DC"],
    need: 1,
  },
  {
    id: 120,
    section: "Symbols and Holidays",
    question: "Where is the Statue of Liberty?",
    answers: [
      "New York (Harbor)",
      "New York Harbor",
      "New York",
      "Liberty Island",
      "New Jersey",
      "Near New York City",
      "On the Hudson (River)",
      "Hudson River",
    ],
    need: 1,
  },
  {
    id: 121,
    section: "Symbols and Holidays",
    question: "Why does the flag have 13 stripes?",
    answers: [
      "(Because there were) 13 original colonies",
      "Because there were 13 original colonies",
      "(Because the stripes) represent the original colonies",
      "Because the stripes represent the original colonies",
    ],
    need: 1,
    special65: true,
  },
  {
    id: 122,
    section: "Symbols and Holidays",
    question: "Why does the flag have 50 stars?",
    answers: [
      "(Because there is) one star for each state",
      "Because there is one star for each state",
      "(Because) each star represents a state",
      "Because each star represents a state",
      "(Because there are) 50 states",
      "Because there are 50 states",
    ],
    need: 1,
  },
  {
    id: 123,
    section: "Symbols and Holidays",
    question: "What is the name of the national anthem?",
    answers: ["The Star-Spangled Banner"],
    need: 1,
  },
  {
    id: 124,
    section: "Symbols and Holidays",
    question: 'The Nation’s first motto was “E Pluribus Unum.” What does that mean?',
    answers: ["Out of many, one", "We all become one"],
    need: 1,
  },
  {
    id: 125,
    section: "Symbols and Holidays",
    question: "What is Independence Day?",
    answers: [
      "A holiday to celebrate U.S. independence (from Britain)",
      "A holiday to celebrate U.S. independence from Britain",
      "The country’s birthday",
      "The country's birthday",
    ],
    need: 1,
  },
  {
    id: 126,
    section: "Symbols and Holidays",
    question: "Name three national U.S. holidays.",
    answers: [
      "New Year’s Day",
      "New Year's Day",
      "Martin Luther King, Jr. Day",
      "Presidents Day (Washington’s Birthday)",
      "Presidents Day",
      "Memorial Day",
      "Juneteenth",
      "Independence Day",
      "Labor Day",
      "Columbus Day",
      "Veterans Day",
      "Thanksgiving Day",
      "Christmas Day",
    ],
    need: 3,
  },
  {
    id: 127,
    section: "Symbols and Holidays",
    question: "What is Memorial Day?",
    answers: ["A holiday to honor soldiers who died in military service"],
    need: 1,
  },
  {
    id: 128,
    section: "Symbols and Holidays",
    question: "What is Veterans Day?",
    answers: [
      "A holiday to honor people in the (U.S.) military",
      "A holiday to honor people in the U.S. military",
      "A holiday to honor people who have served (in the U.S. military)",
      "A holiday to honor people who have served in the U.S. military",
    ],
    need: 1,
  },
];

export function getQuizPool() {
  return civicsQuestions.filter((question) => !question.varies);
}

export function shuffle<T>(items: T[]) {
  const next = [...items];
  for (let i = next.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [next[i], next[j]] = [next[j], next[i]];
  }
  return next;
}

export function uniqueAnswers(question: CivicsQuestion) {
  const seen = new Set<string>();
  return question.answers.filter((answer) => {
    const key = answer.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
