import {
  eventId,
  eventOverlaps,
  NOW_YEAR,
  partsToYear,
  type HistoryCategoryId,
  type HistoryEvent,
} from "@/lib/history-timeline";

function ev(
  category: HistoryCategoryId,
  year: number,
  title: string,
  summary: string,
  significance: 1 | 2 | 3 | 4 | 5,
  extras: {
    endYear?: number;
    projected?: boolean;
    wikipedia?: string;
    wikiTitle?: string;
  } = {},
): HistoryEvent {
  return {
    id: eventId(category, year, title),
    category,
    year,
    title,
    summary,
    significance,
    source: "seed",
    ...extras,
  };
}

const SEED_EVENTS: HistoryEvent[] = [
  ev(
    "empires",
    -2334,
    "Akkadian Empire",
    "Sargon of Akkad unifies Mesopotamian city-states into one of the first recorded empires.",
    5,
    { endYear: -2154 },
  ),
  ev(
    "empires",
    -550,
    "Achaemenid Persian Empire",
    "Cyrus the Great founds an empire stretching from the Aegean to the Indus.",
    5,
    { endYear: -330 },
  ),
  ev(
    "empires",
    -509,
    "Roman Republic",
    "Rome replaces its kings with annually elected magistrates; the republic lasts until Octavian’s settlement.",
    5,
    { endYear: -27 },
  ),
  ev(
    "empires",
    -221,
    "Qin unifies China",
    "Qin Shi Huang ends the Warring States and standardizes writing, roads, and measures.",
    5,
    { endYear: -206 },
  ),
  ev(
    "empires",
    -27,
    "Roman Empire",
    "Augustus ends the republic; the western imperial state lasts until 476 CE.",
    5,
    { endYear: 476 },
  ),
  ev(
    "empires",
    224,
    "Sassanid Empire",
    "Ardashir I overthrows the Parthians; Sasanian Iran lasts until the Arab conquests.",
    5,
    { endYear: 651 },
  ),
  ev(
    "empires",
    330,
    "Eastern Roman / Byzantine Empire",
    "Constantinople becomes the Roman capital; the eastern state continues until 1453.",
    5,
    { endYear: 1453 },
  ),
  ev(
    "empires",
    300,
    "Ghana Empire",
    "A West African trading empire on the Sahel gold and salt routes, before Mali.",
    4,
    { endYear: 1200 },
  ),
  ev(
    "empires",
    618,
    "Tang dynasty",
    "Li Yuan founds a cosmopolitan Chinese empire that sets a high-water mark for medieval East Asia.",
    5,
    { endYear: 907 },
  ),
  ev(
    "empires",
    661,
    "Umayyad Caliphate",
    "The Umayyads rule from Damascus and stretch from Iberia to Central Asia.",
    5,
    { endYear: 750 },
  ),
  ev(
    "empires",
    681,
    "First Bulgarian Empire",
    "Asparuh’s Bulgars found a state that rivals Byzantium in the Balkans.",
    4,
    { endYear: 1018 },
  ),
  ev(
    "empires",
    750,
    "Abbasid Caliphate",
    "The Abbasids move the caliphal center to Iraq; Baghdad becomes a world city until the Mongol sack.",
    5,
    { endYear: 1258 },
  ),
  ev(
    "empires",
    800,
    "Carolingian Empire",
    "Charlemagne is crowned emperor; a Frankish imperial order lasts through the ninth century.",
    4,
    { endYear: 888 },
  ),
  ev(
    "empires",
    802,
    "Khmer Empire",
    "Jayavarman II founds a mainland Southeast Asian empire centered on Angkor.",
    4,
    { endYear: 1431 },
  ),
  ev(
    "empires",
    960,
    "Song dynasty",
    "Zhao Kuangyin reunifies most of China; the Song era is dense with cities, print, and commerce.",
    5,
    { endYear: 1279 },
  ),
  ev(
    "empires",
    962,
    "Holy Roman Empire",
    "Otto I is crowned emperor; a Central European imperial title lasts until 1806.",
    5,
    { endYear: 1806 },
  ),
  ev(
    "empires",
    1206,
    "Mongol Empire",
    "Temüjin is proclaimed Chinggis Khan; Mongol armies soon span Eurasia.",
    5,
    { endYear: 1368 },
  ),
  ev(
    "empires",
    1299,
    "Ottoman Empire",
    "Osman I’s frontier principality grows into a transcontinental empire.",
    5,
    { endYear: 1922 },
  ),
  ev(
    "empires",
    1428,
    "Aztec Triple Alliance",
    "Tenochtitlan, Texcoco, and Tlacopan dominate the Valley of Mexico.",
    4,
    { endYear: 1521 },
  ),
  ev(
    "empires",
    1526,
    "Mughal Empire",
    "Babur wins at Panipat and founds a North Indian imperial dynasty.",
    4,
    { endYear: 1857 },
  ),
  ev(
    "empires",
    1707,
    "Kingdom of Great Britain",
    "The Acts of Union join England and Scotland; a global maritime empire follows.",
    5,
    { endYear: NOW_YEAR },
  ),
  ev(
    "empires",
    1922,
    "Soviet Union",
    "The USSR spans Eurasia until it breaks into independent republics.",
    5,
    { endYear: 1991 },
  ),

  ev(
    "inventions",
    -3200,
    "Writing in Mesopotamia",
    "Cuneiform record-keeping on clay tablets makes states and stories durable.",
    5,
  ),
  ev(
    "inventions",
    -3500,
    "The wheel",
    "Wheeled vehicles appear in Mesopotamia and the steppe, transforming haulage.",
    5,
  ),
  ev(
    "inventions",
    -3000,
    "Control of fire",
    "By the Bronze Age, keeping and kindling fire is already a human universal — cooking, ceramics, and metalwork depend on it.",
    5,
  ),
  ev(
    "inventions",
    -2000,
    "Spoked-wheel chariot",
    "Light horse chariots become the prestige weapon of Bronze Age armies.",
    4,
  ),
  ev(
    "inventions",
    -1200,
    "Iron working",
    "Bloomery iron spreads after the Bronze Age collapse, making metal tools far more common.",
    5,
  ),
  ev(
    "inventions",
    -1050,
    "Phoenician alphabet",
    "A small consonant alphabet becomes the ancestor of later Mediterranean scripts.",
    5,
  ),
  ev(
    "inventions",
    105,
    "Paper in Han China",
    "Court official Cai Lun standardizes paper from plant fibers — cheap, light writing.",
    5,
  ),
  ev(
    "inventions",
    1440,
    "Gutenberg printing press",
    "Movable metal type in Mainz makes books faster and far cheaper to copy.",
    5,
  ),
  ev(
    "inventions",
    1608,
    "Refracting telescope",
    "Dutch spectacle makers and then Galileo turn lenses on the sky.",
    4,
  ),
  ev(
    "inventions",
    1712,
    "Newcomen steam engine",
    "An atmospheric engine pumps water from mines — a first industrial prime mover.",
    5,
  ),
  ev(
    "inventions",
    1796,
    "Smallpox vaccine",
    "Edward Jenner’s cowpox inoculation founds modern vaccination.",
    5,
  ),
  ev(
    "inventions",
    1876,
    "Telephone",
    "Bell’s patent and early exchanges put speech on a wire.",
    4,
  ),
  ev(
    "inventions",
    1903,
    "Powered airplane",
    "The Wright brothers’ Flyer makes a controlled, sustained flight at Kitty Hawk.",
    5,
  ),
  ev(
    "inventions",
    1928,
    "Penicillin",
    "Alexander Fleming notices a mold that kills bacteria; antibiotics follow.",
    5,
  ),
  ev(
    "inventions",
    1947,
    "Transistor",
    "Bell Labs replaces bulky tubes with a solid-state switch — the computer age’s seed.",
    5,
  ),
  ev(
    "inventions",
    1989,
    "World Wide Web",
    "Tim Berners-Lee proposes a hypertext system for sharing documents at CERN.",
    5,
  ),
  ev(
    "inventions",
    partsToYear(2007, 1, 9),
    "iPhone",
    "A pocket computer with a multitouch screen resets phones, software, and media.",
    4,
  ),

  ev(
    "musicians",
    1098,
    "Hildegard of Bingen",
    "Abbess, composer, and visionary whose chants still define medieval sacred music.",
    4,
    { endYear: 1179 },
  ),
  ev(
    "musicians",
    1685,
    "Johann Sebastian Bach",
    "Born in Eisenach; later cantatas, passions, and keyboard works shape Western harmony.",
    5,
    { endYear: 1750 },
  ),
  ev(
    "musicians",
    1756,
    "Wolfgang Amadeus Mozart",
    "A Salzburg prodigy whose operas and concertos become Classical-period landmarks.",
    5,
    { endYear: 1791 },
  ),
  ev(
    "musicians",
    1770,
    "Ludwig van Beethoven",
    "Bonn-born composer who stretches the symphony from Classical into Romantic.",
    5,
    { endYear: 1827 },
  ),
  ev(
    "musicians",
    1810,
    "Frédéric Chopin",
    "Polish pianist-composer who makes the piano the Romantic era’s intimate voice.",
    4,
    { endYear: 1849 },
  ),
  ev(
    "musicians",
    1899,
    "Duke Ellington",
    "Composer-bandleader who writes a jazz repertoire as ambitious as any symphony.",
    4,
    { endYear: 1974 },
  ),
  ev(
    "musicians",
    1936,
    "Billie Holiday records Summertime",
    "Holiday’s phrasing on early sessions helps define jazz singing.",
    3,
  ),
  ev(
    "musicians",
    1962,
    "The Beatles’ first single",
    "Love Me Do begins a pop career that rewrites recording, fandom, and songwriting.",
    5,
    { endYear: 1970 },
  ),
  ev(
    "musicians",
    1965,
    "Bob Dylan goes electric",
    "Newport and Highway 61 Revisited fuse folk lyric with rock band.",
    4,
  ),
  ev(
    "musicians",
    1979,
    "Rapper’s Delight",
    "The Sugarhill Gang’s hit takes hip-hop from Bronx parties onto the radio.",
    4,
  ),
  ev(
    "musicians",
    1982,
    "Thriller",
    "Michael Jackson’s album and videos make pop a global visual medium.",
    4,
  ),

  ev(
    "wars",
    -1274,
    "Battle of Kadesh",
    "Ramesses II and Muwatalli II fight the best-documented chariot battle of the Bronze Age.",
    5,
  ),
  ev(
    "wars",
    -1200,
    "Bronze Age collapse",
    "Palaces from Greece to the Levant fall; Sea Peoples and inland wars remake the eastern Mediterranean.",
    5,
    { endYear: -1150 },
  ),
  ev(
    "wars",
    -499,
    "Greco-Persian Wars",
    "Greek city-states resist Achaemenid invasions at Marathon, Salamis, and Plataea.",
    4,
    { endYear: -449 },
  ),
  ev(
    "wars",
    -264,
    "Punic Wars",
    "Rome and Carthage fight three wars for the western Mediterranean.",
    5,
    { endYear: -146 },
  ),
  ev(
    "wars",
    717,
    "Umayyad siege of Constantinople",
    "Maslama’s Umayyad army and fleet fail to take the Byzantine capital; Greek fire and the Theodosian Walls hold.",
    4,
    { endYear: 718 },
  ),
  ev(
    "wars",
    732,
    "Battle of Tours",
    "Charles Martel’s Franks halt an Umayyad raid near Poitiers — a war, not an empire.",
    4,
  ),
  ev(
    "wars",
    1096,
    "First Crusade",
    "Latin armies take Jerusalem; a long era of crusading and Levantine states begins.",
    4,
    { endYear: 1099 },
  ),
  ev(
    "wars",
    1337,
    "Hundred Years’ War",
    "England and France contest the French crown across four generations.",
    4,
    { endYear: 1453 },
  ),
  ev(
    "wars",
    1618,
    "Thirty Years’ War",
    "A Central European war of religion and state hollows out the Holy Roman Empire.",
    5,
    { endYear: 1648 },
  ),
  ev(
    "wars",
    1775,
    "American Revolutionary War",
    "Thirteen colonies win independence from Britain with French help.",
    5,
    { endYear: 1783 },
  ),
  ev(
    "wars",
    1803,
    "Napoleonic Wars",
    "France under Napoleon fights shifting coalitions until Waterloo.",
    5,
    { endYear: 1815 },
  ),
  ev(
    "wars",
    1861,
    "American Civil War",
    "The United States splits over slavery and union; emancipation follows Union victory.",
    5,
    { endYear: 1865 },
  ),
  ev(
    "wars",
    1914,
    "World War I",
    "A European alliance war becomes a global industrial slaughter until 1918.",
    5,
    { endYear: 1918 },
  ),
  ev(
    "wars",
    1939,
    "World War II",
    "Axis and Allied coalitions fight on every inhabited continent.",
    5,
    { endYear: 1945 },
  ),
  ev(
    "wars",
    partsToYear(1944, 6, 6),
    "D-Day",
    "Allied forces land in Normandy on 6 June 1944, opening the Western Front in France.",
    5,
  ),
  ev(
    "wars",
    1947,
    "Cold War",
    "The United States and Soviet Union contest influence without direct all-out war.",
    5,
    { endYear: 1991 },
  ),

  ev(
    "explorations",
    -138,
    "Zhang Qian’s missions",
    "Han envoys open routes that later writers call the Silk Road.",
    4,
    { endYear: -126 },
  ),
  ev(
    "explorations",
    1405,
    "Zheng He’s first voyage",
    "Ming treasure fleets sail the Indian Ocean as far as East Africa.",
    4,
    { endYear: 1433 },
  ),
  ev(
    "explorations",
    1492,
    "Columbus reaches the Caribbean",
    "A Castilian-sponsored crossing links Afro-Eurasia to the Americas — with catastrophic cost to Indigenous peoples.",
    5,
    { endYear: 1504 },
  ),
  ev(
    "explorations",
    1498,
    "Vasco da Gama reaches India",
    "A sea route around Africa ties Lisbon to the Indian Ocean spice trade.",
    5,
    { endYear: 1499 },
  ),
  ev(
    "explorations",
    1519,
    "Magellan–Elcano circumnavigation",
    "One surviving ship proves the oceans connect; Magellan dies in the Philippines.",
    5,
    { endYear: 1522 },
  ),
  ev(
    "explorations",
    1768,
    "Cook’s Endeavour voyage",
    "James Cook charts the Pacific, New Zealand, and Australia’s east coast.",
    4,
    { endYear: 1771 },
  ),
  ev(
    "explorations",
    1804,
    "Lewis and Clark expedition",
    "A U.S. Corps of Discovery crosses the continent to the Pacific Northwest.",
    3,
    { endYear: 1806 },
  ),
  ev(
    "explorations",
    1911,
    "Amundsen at the South Pole",
    "A Norwegian team is first to the geographic South Pole.",
    4,
  ),
  ev(
    "explorations",
    partsToYear(1969, 7, 20),
    "Apollo 11 Moon landing",
    "Armstrong and Aldrin walk on the Moon; Collins orbits above.",
    5,
  ),
  ev(
    "explorations",
    1977,
    "Voyager launches",
    "Twin probes fly the outer planets; Voyager 1 later enters interstellar space.",
    4,
    { endYear: NOW_YEAR },
  ),
  ev(
    "explorations",
    2012,
    "Curiosity lands on Mars",
    "A car-sized rover begins a long chemistry and geology survey of Gale Crater.",
    3,
    { endYear: NOW_YEAR },
  ),

  ev(
    "science",
    -300,
    "Euclid’s Elements",
    "A systematic geometry textbook that remains a model of proof for two millennia.",
    5,
    { endYear: -270 },
  ),
  ev(
    "science",
    1543,
    "Copernican Revolution",
    "De revolutionibus places the Sun at the center of the known planets.",
    5,
  ),
  ev(
    "science",
    1687,
    "Newton’s Principia",
    "Laws of motion and universal gravitation unify earth and sky.",
    5,
  ),
  ev(
    "science",
    1859,
    "On the Origin of Species",
    "Darwin argues that natural selection explains the diversity of life.",
    5,
  ),
  ev(
    "science",
    1869,
    "Periodic table",
    "Mendeleev arranges the elements so missing ones can be predicted.",
    4,
  ),
  ev(
    "science",
    1905,
    "Einstein’s annus mirabilis",
    "Papers on photons, Brownian motion, and special relativity recast physics.",
    5,
  ),
  ev(
    "science",
    1928,
    "Fleming and penicillin",
    "A contaminated dish leads to the first widely useful antibiotic.",
    4,
  ),
  ev(
    "science",
    1953,
    "Structure of DNA",
    "Watson, Crick, Franklin, and Wilkins describe the double helix.",
    5,
  ),
  ev(
    "science",
    1969,
    "Apollo science return",
    "Moon rocks give the solar system a dated, sample-based history.",
    3,
  ),
  ev(
    "science",
    2012,
    "Higgs boson",
    "CERN’s LHC confirms the particle that gives other particles mass in the Standard Model.",
    4,
  ),
  ev(
    "science",
    2012,
    "CRISPR gene editing",
    "Doudna, Charpentier, and others turn a bacterial immune system into an editing tool.",
    5,
  ),

  ev(
    "art",
    -447,
    "Parthenon begun",
    "Athens builds the temple that becomes a shorthand for Classical sculpture and architecture.",
    5,
    { endYear: -432 },
  ),
  ev(
    "art",
    -210,
    "Terracotta Army",
    "Thousands of life-size soldiers are buried with Qin Shi Huang.",
    4,
  ),
  ev(
    "art",
    537,
    "Hagia Sophia dedicated",
    "Justinian’s great church sets a Byzantine standard for dome and light.",
    5,
  ),
  ev(
    "art",
    1503,
    "Leonardo paints the Mona Lisa",
    "A Florentine portrait becomes the most visited painting in the world.",
    5,
  ),
  ev(
    "art",
    1504,
    "Michelangelo’s David",
    "A colossal marble nude becomes the emblem of High Renaissance Florence.",
    5,
  ),
  ev(
    "art",
    1642,
    "Rembrandt’s Night Watch",
    "A militia portrait that treats group portraiture like theater.",
    4,
  ),
  ev(
    "art",
    1874,
    "First Impressionist exhibition",
    "Monet, Renoir, Degas and others show modern life outside the Salon.",
    5,
    { endYear: 1886 },
  ),
  ev(
    "art",
    1907,
    "Picasso’s Les Demoiselles d’Avignon",
    "A rupture that helps open Cubism and 20th-century painting.",
    5,
  ),
  ev(
    "art",
    1917,
    "Fountain",
    "Duchamp’s readymade urinal asks what counts as a work of art.",
    4,
  ),
  ev(
    "art",
    1962,
    "Warhol’s soup cans",
    "Campbell’s canvases make commerce and celebrity a Fine Art subject.",
    4,
  ),

  ev(
    "sports",
    -776,
    "First recorded Olympic Games",
    "A footrace at Olympia begins a four-year festival of Greek athletics.",
    5,
  ),
  ev(
    "sports",
    1863,
    "Football Association founded",
    "London clubs write the laws that become association football.",
    5,
  ),
  ev(
    "sports",
    1896,
    "First modern Olympics",
    "Athens revives the Games as an international amateur meeting.",
    5,
  ),
  ev(
    "sports",
    1903,
    "First World Series",
    "Boston and Pittsburgh meet in a postseason that becomes baseball’s title.",
    3,
  ),
  ev(
    "sports",
    1930,
    "First FIFA World Cup",
    "Uruguay hosts and wins the first football tournament of nations.",
    5,
  ),
  ev(
    "sports",
    1947,
    "Jackie Robinson debuts",
    "Robinson plays for the Brooklyn Dodgers, breaking MLB’s color line.",
    5,
  ),
  ev(
    "sports",
    1967,
    "Super Bowl I",
    "Green Bay beats Kansas City in the first AFL–NFL championship game later branded Super Bowl.",
    3,
  ),
  ev(
    "sports",
    1972,
    "Title IX",
    "U.S. law bars sex discrimination in federally funded education, transforming school sports.",
    4,
    { endYear: NOW_YEAR },
  ),
  ev(
    "sports",
    1980,
    "Miracle on Ice",
    "The U.S. amateur hockey team upsets the Soviet Union at Lake Placid.",
    3,
  ),
  ev(
    "sports",
    1991,
    "First FIFA Women's World Cup",
    "China hosts; the United States wins the first official women’s tournament.",
    4,
  ),
  ev(
    "sports",
    2008,
    "Usain Bolt in Beijing",
    "Bolt’s 100 m and 200 m world records reset what sprinting looks like.",
    3,
  ),
  ev(
    "sports",
    2016,
    "Simone Biles in Rio",
    "Biles wins four Olympic golds and becomes the face of modern gymnastics.",
    3,
  ),

  ev(
    "explorations",
    2027,
    "Artemis lunar return (projected)",
    "NASA and partners aim to land crew on the Moon again under the Artemis program.",
    3,
    { projected: true },
  ),
  ev(
    "science",
    2040,
    "Commercial fusion pilots (projected)",
    "Several national and private projects target net-power demonstration plants by mid-century.",
    3,
    { projected: true },
  ),
  ev(
    "explorations",
    2040,
    "Crewed Mars landing (projected)",
    "Space agencies and firms publish timelines for the first human landing on Mars.",
    4,
    { projected: true },
  ),
];

/** Canonical English Wikipedia titles for well-known seeds. */
const SEED_WIKIPEDIA: Record<string, string> = {
  "Akkadian Empire": "Akkadian Empire",
  "Achaemenid Persian Empire": "Achaemenid Empire",
  "Roman Republic": "Roman Republic",
  "Qin unifies China": "Qin dynasty",
  "Roman Empire": "Roman Empire",
  "Sassanid Empire": "Sasanian Empire",
  "Eastern Roman / Byzantine Empire": "Byzantine Empire",
  "Ghana Empire": "Ghana Empire",
  "Tang dynasty": "Tang dynasty",
  "Umayyad Caliphate": "Umayyad Caliphate",
  "First Bulgarian Empire": "First Bulgarian Empire",
  "Abbasid Caliphate": "Abbasid Caliphate",
  "Carolingian Empire": "Carolingian Empire",
  "Khmer Empire": "Khmer Empire",
  "Song dynasty": "Song dynasty",
  "Holy Roman Empire": "Holy Roman Empire",
  "Mongol Empire": "Mongol Empire",
  "Ottoman Empire": "Ottoman Empire",
  "Aztec Triple Alliance": "Aztec Empire",
  "Mughal Empire": "Mughal Empire",
  "Kingdom of Great Britain": "Kingdom of Great Britain",
  "Soviet Union": "Soviet Union",
  "Writing in Mesopotamia": "Cuneiform",
  "The wheel": "Wheel",
  "Control of fire": "Control of fire by early humans",
  "Spoked-wheel chariot": "Chariot",
  "Iron working": "Iron Age",
  "Phoenician alphabet": "Phoenician alphabet",
  "Paper in Han China": "Cai Lun",
  "Gutenberg printing press": "Printing press",
  "Refracting telescope": "Refracting telescope",
  "Newcomen steam engine": "Newcomen atmospheric engine",
  "Smallpox vaccine": "Smallpox vaccine",
  Telephone: "Telephone",
  "Powered airplane": "Wright Flyer",
  Penicillin: "Penicillin",
  Transistor: "Transistor",
  "World Wide Web": "World Wide Web",
  iPhone: "iPhone",
  "Hildegard of Bingen": "Hildegard of Bingen",
  "Johann Sebastian Bach": "Johann Sebastian Bach",
  "Wolfgang Amadeus Mozart": "Wolfgang Amadeus Mozart",
  "Ludwig van Beethoven": "Ludwig van Beethoven",
  "Frédéric Chopin": "Frédéric Chopin",
  "Duke Ellington": "Duke Ellington",
  "Billie Holiday records Summertime": "Billie Holiday",
  "The Beatles’ first single": "The Beatles",
  "Bob Dylan goes electric": "Bob Dylan",
  "Rapper’s Delight": "Rapper's Delight",
  Thriller: "Thriller (album)",
  "Battle of Kadesh": "Battle of Kadesh",
  "Bronze Age collapse": "Late Bronze Age collapse",
  "Greco-Persian Wars": "Greco-Persian Wars",
  "Punic Wars": "Punic Wars",
  "Umayyad siege of Constantinople": "Siege of Constantinople (717–718)",
  "Battle of Tours": "Battle of Tours",
  "First Crusade": "First Crusade",
  "Hundred Years’ War": "Hundred Years' War",
  "Thirty Years’ War": "Thirty Years' War",
  "American Revolutionary War": "American Revolutionary War",
  "Napoleonic Wars": "Napoleonic Wars",
  "American Civil War": "American Civil War",
  "World War I": "World War I",
  "World War II": "World War II",
  "D-Day": "Normandy landings",
  "Cold War": "Cold War",
  "Zhang Qian’s missions": "Zhang Qian",
  "Zheng He’s first voyage": "Zheng He",
  "Columbus reaches the Caribbean": "Christopher Columbus",
  "Vasco da Gama reaches India": "Vasco da Gama",
  "Magellan–Elcano circumnavigation": "Magellan expedition",
  "Cook’s Endeavour voyage": "First voyage of James Cook",
  "Lewis and Clark expedition": "Lewis and Clark Expedition",
  "Amundsen at the South Pole": "Amundsen's South Pole expedition",
  "Apollo 11 Moon landing": "Apollo 11",
  "Voyager launches": "Voyager program",
  "Curiosity lands on Mars": "Curiosity (rover)",
  "Euclid’s Elements": "Euclid's Elements",
  "Copernican Revolution": "Copernican Revolution",
  "Newton’s Principia": "Philosophiæ Naturalis Principia Mathematica",
  "On the Origin of Species": "On the Origin of Species",
  "Periodic table": "Periodic table",
  "Einstein’s annus mirabilis": "Annus mirabilis papers",
  "Fleming and penicillin": "Alexander Fleming",
  "Structure of DNA": "Nucleic acid double helix",
  "Apollo science return": "Moon rock",
  "Higgs boson": "Higgs boson",
  "CRISPR gene editing": "CRISPR gene editing",
  "Parthenon begun": "Parthenon",
  "Terracotta Army": "Terracotta Army",
  "Hagia Sophia dedicated": "Hagia Sophia",
  "Leonardo paints the Mona Lisa": "Mona Lisa",
  "Michelangelo’s David": "David (Michelangelo)",
  "Rembrandt’s Night Watch": "The Night Watch",
  "First Impressionist exhibition": "Impressionism",
  "Picasso’s Les Demoiselles d’Avignon": "Les Demoiselles d'Avignon",
  Fountain: "Fountain (Duchamp)",
  "Warhol’s soup cans": "Campbell's Soup Cans",
  "First recorded Olympic Games": "Ancient Olympic Games",
  "Football Association founded": "The Football Association",
  "First modern Olympics": "1896 Summer Olympics",
  "First World Series": "1903 World Series",
  "First FIFA World Cup": "1930 FIFA World Cup",
  "Jackie Robinson debuts": "Jackie Robinson",
  "Super Bowl I": "Super Bowl I",
  "Title IX": "Title IX",
  "Miracle on Ice": "Miracle on Ice",
  "First FIFA Women's World Cup": "1991 FIFA Women's World Cup",
  "Usain Bolt in Beijing": "Usain Bolt",
  "Simone Biles in Rio": "Simone Biles",
  "Artemis lunar return (projected)": "Artemis program",
  "Commercial fusion pilots (projected)": "Fusion power",
  "Crewed Mars landing (projected)": "Human mission to Mars",
};

export const historySeedEvents: HistoryEvent[] = SEED_EVENTS.map((event) => {
  const wikipedia = SEED_WIKIPEDIA[event.title];
  return wikipedia ? { ...event, wikipedia } : event;
});

/** Older seed ids/titles that must not linger in Mongo window caches. */
export const RETIRED_HISTORY_EVENT_IDS = new Set([
  "empires--27-roman-empire-begins",
  "empires-330-constantinople-founded",
]);

export const RETIRED_HISTORY_EVENT_TITLES = new Set([
  "Roman Empire begins",
]);

export function isRetiredHistoryEvent(event: {
  id: string;
  title?: string;
}) {
  if (RETIRED_HISTORY_EVENT_IDS.has(event.id)) return true;
  if (event.title && RETIRED_HISTORY_EVENT_TITLES.has(event.title)) return true;
  return false;
}

export function withoutRetiredHistoryEvents<T extends { id: string; title?: string }>(
  events: T[],
) {
  return events.filter((event) => !isRetiredHistoryEvent(event));
}

export function seedEventsFor(
  category: string,
  start: number,
  end: number,
) {
  return historySeedEvents.filter(
    (event) => event.category === category && eventOverlaps(event, start, end),
  );
}
