export type SpellingLang = "en" | "es" | "fr";

export type SpellingList = {
  id: SpellingLang;
  label: string;
  locale: string;
  words: string[];
};

export const spellingLists: SpellingList[] = [
  {
    id: "en",
    label: "English",
    locale: "en-US",
    words: [
      "because",
      "friend",
      "people",
      "school",
      "through",
      "enough",
      "thought",
      "beautiful",
      "wednesday",
      "february",
      "receive",
      "believe",
      "island",
      "knight",
      "science",
      "neighbor",
      "although",
      "separate",
      "necessary",
      "restaurant",
      "definitely",
      "conscience",
      "occurrence",
      "accommodate",
      "rhythm",
      "height",
      "weight",
      "foreign",
      "government",
      "environment",
      "knowledge",
      "privilege",
      "calendar",
      "library",
      "chocolate",
      "sandwich",
      "dinosaur",
      "elephant",
      "butterfly",
      "mountain",
    ],
  },
  {
    id: "es",
    label: "Español",
    locale: "es-ES",
    words: [
      "amigo",
      "escuela",
      "familia",
      "gracias",
      "corazón",
      "pequeño",
      "árbol",
      "mañana",
      "español",
      "niño",
      "ciudad",
      "tiempo",
      "también",
      "rápido",
      "música",
      "jardín",
      "feliz",
      "camino",
      "biblioteca",
      "mariposa",
      "cumpleaños",
      "chocolate",
      "hospital",
      "pájaro",
      "flor",
      "playa",
      "montaña",
      "ventana",
      "cocina",
      "zapato",
      "camisa",
      "perro",
      "gato",
      "casa",
      "agua",
      "leche",
      "queso",
      "libro",
      "lápiz",
      "número",
    ],
  },
  {
    id: "fr",
    label: "Français",
    locale: "fr-FR",
    words: [
      "bonjour",
      "ami",
      "école",
      "famille",
      "merci",
      "cœur",
      "petit",
      "arbre",
      "demain",
      "français",
      "enfant",
      "ville",
      "temps",
      "aussi",
      "rapide",
      "musique",
      "jardin",
      "heureux",
      "chemin",
      "bibliothèque",
      "papillon",
      "anniversaire",
      "chocolat",
      "hôpital",
      "oiseau",
      "fleur",
      "plage",
      "montagne",
      "fenêtre",
      "cuisine",
      "chaussure",
      "chien",
      "chat",
      "maison",
      "eau",
      "lait",
      "fromage",
      "livre",
      "crayon",
      "numéro",
    ],
  },
];

export function getSpellingList(id: SpellingLang) {
  return spellingLists.find((list) => list.id === id) ?? spellingLists[0];
}
